name: 'Azure Test Action'
description: 'An example action for deploying to Azure.'
inputs:
  azure-webapp-name:
    description: 'Name of the Azure Web App'
    required: true
  azure-webapp-package-path:
    description: 'Path to the web app package'
    required: true
  azure-publish-profile:
    description: 'Azure publish profile'
    required: true

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'
