- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(288bf2a2-a366-4ff9-a639-8d96a2ef3886)'
    appType: 'webApp'
    appName: 'webcoba'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'