name: Build and Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env:
  AZURE_WEBAPP_NAME: devoptest
  AZURE_WEBAPP_PACKAGE_PATH: 'publishedn'
  NETCORE_VERSION: '6.*.*'
  AZURE_WEBAPP_PUBLISH_PROFILE: '<publishData><publishProfile profileName="devoptest - Web Deploy" publishMethod="MSDeploy" publishUrl="devoptest-anchg9hraug6btcb.scm.canadacentral-01.azurewebsites.net:443" msdeploySite="devoptest" userName="$devoptest" userPWD="zwReZ8SPA3PR5C5hMvGjR7hExcxiKNrbiNJKl82sK5jPlasFg1sexG2K8NSo" destinationAppUrl="https://devoptest-anchg9hraug6btcb.canadacentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="devoptest - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-yt1-033.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="devoptest\$devoptest" userPWD="zwReZ8SPA3PR5C5hMvGjR7hExcxiKNrbiNJKl82sK5jPlasFg1sexG2K8NSo" destinationAppUrl="https://devoptest-anchg9hraug6btcb.canadacentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="devoptest - Zip Deploy" publishMethod="ZipDeploy" publishUrl="devoptest-anchg9hraug6btcb.scm.canadacentral-01.azurewebsites.net:443" userName="$devoptest" userPWD="zwReZ8SPA3PR5C5hMvGjR7hExcxiKNrbiNJKl82sK5jPlasFg1sexG2K8NSo" destinationAppUrl="https://devoptest-anchg9hraug6btcb.canadacentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'

jobs:
  build:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      
      - name: Restore packages
        run: dotnet restore
        working-directory: PartyInvites

      - name: Build app
        run: dotnet build --configuration Release --no-restore
        working-directory: PartyInvites

      - name: Test app
        run: dotnet test --no-build
        working-directory: PartyInvites

      - name: Publish app for deploy
        run: dotnet publish --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        working-directory: PartyInvites

      - name: Verify published directory
        run: Get-ChildItem -Path PartyInvites/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: PartyInvites/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: webapp
          path: PartyInvites/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
