name: Build and Deploy PartyInvites

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the "main" branch

jobs:
  build-and-deploy:
    runs-on: windows-latest
    working-directory: ./PartyInvites
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PartyInvites20241105083153'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_457292A92CDA40CD87A57E77291063A6 }}
